---
- name: Install Deployment Prerequisites
  hosts: flask_servers
  become: true
  gather_facts: true

  tasks:
    - name: Run Prerequisites Installation
      ansible.builtin.include_tasks: ../tasks/prerequisites.yaml

    - name: Deploy course-store Repository
      ansible.builtin.include_tasks: ../tasks/repository.yaml

    - name: Deploy Application using Docker Compose
      ansible.builtin.import_tasks: ../tasks/composefile.yaml

    - name: Verify Application Deployment
      ansible.builtin.import_tasks: ../tasks/verify.yaml
       