[flask_servers]

vm-01 ansible_host=102.37.116.251 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/vm-01_key.pem
vm-02 ansible_host=40.123.249.88 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/vm-02_key.pem

[flask_servers:vars]

ansible_python_interpreter=/usr/bin/python3